[%s] NOTICE: [pool aaaa] 'user' directive is ignored when FPM is not running as root
[%s] NOTICE: [pool bbbb] 'user' directive is ignored when FPM is not running as root
[%s] NOTICE: [pool cccc] 'user' directive is ignored when FPM is not running as root
[%s] NOTICE: [pool dddd] 'user' directive is ignored when FPM is not running as root
[%s] NOTICE: [pool eeee] 'user' directive is ignored when FPM is not running as root
[%s] NOTICE: fpm is running, pid %d
[%s] NOTICE: ready to handle connections
OK cccc
OK aaaa
OK eeee
OK dddd
OK bbbb
[%s] NOTICE: Terminating ...
[%s] NOTICE: exiting, bye-bye!
Done